### ISSUE TITLE
关于致远OA漏洞扫描利用

### ISSUE THREAD

**Issue by kaiwen007** [xfiftyone/xfiftyone.github.io#1]
我扫出来漏洞了，但是不太会利用，能与您探讨一下吗？

**Comment by HOLYshitIjustWANTaNAMEFFFFFFFuck** [comment]
蝇蝇蝇

**Comment by xfiftyone** [comment]
工具探测存在误报的可能，建议手工验证一下。

**Comment by kaiwen007** [comment]
扫描到这个漏洞。

执行无果，然后就不会了，哈哈哈。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xfiftyone/xfiftyone.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月22日(星期三) 晚上10:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xfiftyone/xfiftyone.github.io] 关于致远OA漏洞扫描利用 (Issue xfiftyone/xfiftyone.github.io#1)





 
工具探测存在误报的可能，建议手工验证一下。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
